diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('applications/', include('applications.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Учёт заявок'

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about')
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'main/main.html')

def about(request):
    return render(request, 'main/about.html')

main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}О сайте{% endblock %}

{% block body %}
<div class="features">
        <h1>О сайте</h1>
        <p>На сайте представлен функционал передачи заявки на специалиста для предоставление услуги на подключение к сети Интернет, а также на подключение/ремонт телефонной связи.</p>
        <p>ОАО РЖД – это один из ведущих провайдеров услуг подключения к сети интернет и настройки/ремонта телефонной связи в России. Наша компания обладает широким опытом в предоставлении услуг связи и уделяет особое внимание развитию технологических решений для улучшения качества связи и удовлетворения потребностей клиентов в сфере коммуникаций.</p>
        <p>Мы постоянно совершенствуем наши сервисы, следим за тенденциями в сфере связи и внедряем инновационные технологии для обеспечения надежного и быстрого интернет-подключения, а также качественной телефонной связи.</p>
        <p>Нашей главной целью является удовлетворение потребностей наших клиентов в области связи. Мы стремимся предоставлять высококачественные услуги, оперативно реагировать на запросы и обеспечивать надежное подключение к сетям интернет и телефонии.</p>
        <p>Центр технического обслуживания (ЦТО) нашей компании занимается профессиональной настройкой, обслуживанием и ремонтом сетей связи. Наши специалисты – это опытные профессионалы, готовые помочь вам в любое время и решить любые технические проблемы.
        Мы гордимся нашим коллективом специалистов, который стремится к высокому качеству обслуживания и индивидуальному подходу к каждому клиенту. Мы ценим доверие наших заказчиков и всегда готовы помочь вам!</p>
        <a href="{% url 'home' %}"><button class="btn btn-danger"><i class="bi bi-house-door-fill"></i> На главную </button> </a>
    </div>
{% endblock %}

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel = "stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel = "stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/_rzd_logo.jpg' %}" alt="Логотип">
        <span class="logo"> РЖД</span>
        <h3>Навигация</h3>
        <ul>
            {% if user.is_authenticated %}
            <li class="last"><a href="{% url 'users:profile' %}"> <i class="bi bi-person-fill"></i> {{ user.username }} </a>
                | <a href="{% url 'users:logout' %}"> <i class="bi bi-box-arrow-left"></i> Выйти</a></li>
            {% else %}
            <li class="last"><a href="{% url 'users:login' %}"> <i class="bi bi-box-arrow-right"></i> Войти</a>
                | <a href="{% url 'users:register' %}"> <i class="bi bi-box-arrow-up"></i> Регистрация</a></li>
            {% endif %}
            <a href="{% url 'home' %}"><li><i class="bi bi-house-door-fill"></i> Главная</li></a>
            <a href="{% url 'about' %}"><li><i class="bi bi-person-vcard-fill"></i> О сайте</li></a>
            <a href="{% url 'applications_home' %}"><li><i class="bi bi-postcard-fill"></i> Заявки </li></a>
            <li><i class="bi bi-send"></i> Наша почта: <a href="mailto:cto@css.rzd.ru">cto@css.rzd.ru</a></li>

        </ul>
    </aside>
    <main>
        {% block body %}
        <h1>Главная страница</h1>
        <p>Главная страница</p>
        {% endblock %}
    </main>

</body>
</html>

main/templates/main/main.html
{% extends 'main/layout.html' %}

{% block title %}Главная страница{% endblock %}

{% block body %}
    <div class="features">
        <h1>Главная страница</h1>
        <p>Данный WEB-интерфейс представляет собой удобный способ передачи заявки на специалиста для предоставление услуги на подключение к сети Интернет, а также на подключение/ремонт телефонной связи.</p>
        <p>Для создание заявки необходимо нажать на кнопку "Создать заявку". Далее у вас откроется окно для создания заявки. Ваши заявки можно посмотреть в панели навигации "Заявки".</p>
        <a href="{% url 'create' %}"><button class="btn btn-warning"> <i class="bi bi-plus-circle"></i> Создать заявку</button></a>

    </div>
{% endblock %}